apiVersion: v1
kind: Service
metadata:
  name: rules-engine-frontend-service
spec:
  type: NodePort
  ports:
  - port: 31243
    targetPort: 31243
    nodePort: 31243
    protocol: TCP
  selector:
    app: rules-engine-frontend